apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: echo-frontend-appset
  namespace: openshift-gitops
spec:
  generators:
    - git:
        directories:
          - path: week3/day17/app/*
        repoURL: 'https://github.com/sudhishmk/argocd-learning.git'
        revision: HEAD
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      destination:
        namespace: '{{path.basename}}'
        server: 'https://kubernetes.default.svc'
      ignoreDifferences:
        - group: argoproj.io
          jsonPointers:
            - /metadata/labels/mutated-by
          kind: Rollout
      project: echo-apps
      source:
        path: '{{path}}/overlays/dev'
        plugin:
          env:
            - name: AVP_K8S_ROLE
              value: vplugin
            - name: AVP_TYPE
              value: vault
            - name: AVP_VAULT_ADDR
              value: 'http://172.30.189.194:8200'
            - name: AVP_AUTH_TYPE
              value: k8s
          name: argocd-vault-plugin
        repoURL: 'https://github.com/sudhishmk/argocd-learning.git'
        targetRevision: HEAD
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
