apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: echo-frontend
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-frontend
  template:
    metadata:
      labels:
        app: echo-frontend
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: nginx
        image: public.ecr.aws/bitnami/nginx:1.25 # Using a specific version is good practice
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL # Drop all linux capabilities
        ports:
        - containerPort: 80
  strategy:
    canary:
      steps:
      - setWeight: 25
      - pause: { duration: 30s } # Pause for 30s then auto-promote
