apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: dbbackups.mycorp.com
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  group: mycorp.com
  names:
    kind: DbBackup
    plural: dbbackups
    singular: dbbackup
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              database: {type: string}
          status:
            type: object
            properties:
              phase: {type: string}
    served: true
    storage: true
